# 1 "map.c"
static const char __T0[50];
static const char __T1[22];
static const char __T2[39];
static const char __T3[47];
static const char __T4[39];
static const char __T5[22];
static const char __T11[27];
static const char __T12[29];
static const char __T13[46];
static const char __T14[42];
static const char __T15[39];
static const char __T16[38];
static const char __T17[45];
static const char __T18[44];
static const char __T0[50] = "int map_create(pe_s *, coords_s *, int, map_s **)";
static const char __T1[22] = "int map_free(map_s *)";
static const char __T2[39] = "int map_memcpy(map_s *, hipMemcpyKind)";
static const char __T3[47] = "int map_init_io_info(map_s *, int *, int, int)";
static const char __T4[39] = "int map_io_info(map_s *, io_info_s **)";
static const char __T5[22] = "int map_halo(map_s *)";
static const char __T11[27] = "int map_pm(map_s *, int *)";
static const char __T12[29] = "int map_pm_set(map_s *, int)";
static const char __T13[46] = "int map_volume_allreduce(map_s *, int, int *)";
static const char __T14[42] = "int map_volume_local(map_s *, int, int *)";
static const char __T15[39] = "int map_write(_IO_FILE *, int, void *)";
static const char __T16[38] = "int map_read(_IO_FILE *, int, void *)";
static const char __T17[45] = "int map_write_ascii(_IO_FILE *, int, void *)";
static const char __T18[44] = "int map_read_ascii(_IO_FILE *, int, void *)";
