# 1 "surfactant.c"
static const char __T0[94];
static const char __T1[44];
static const char __T2[55];
static const char __T3[73];
static const char __T4[71];
static const char __T5[55];
static const char __T6[53];
static const char __T7[67];
static const char __T8[58];
static const char __T9[56];
static const char __T10[63];
static const char __T0[94] = "int fe_surfactant1_create(pe_s *, coords_s *, field_s *, field_grad_s *, fe_surfactant1_s **)";
static const char __T1[44] = "int fe_surfactant1_free(fe_surfactant1_s *)";
static const char __T2[55] = "int fe_surfactant1_target(fe_surfactant1_s *, fe_s **)";
static const char __T3[73] = "int fe_surfactant1_param_set(fe_surfactant1_s *, fe_surfactant1_param_s)";
static const char __T4[71] = "int fe_surfactant1_param(fe_surfactant1_s *, fe_surfactant1_param_s *)";
static const char __T5[55] = "int fe_surfactant1_sigma(fe_surfactant1_s *, double *)";
static const char __T6[53] = "int fe_surfactant1_xi0(fe_surfactant1_s *, double *)";
static const char __T7[67] = "int fe_surfactant1_langmuir_isotherm(fe_surfactant1_s *, double *)";
static const char __T8[58] = "int fe_surfactant1_fed(fe_surfactant1_s *, int, double *)";
static const char __T9[56] = "int fe_surfactant_mu(fe_surfactant1_s *, int, double *)";
static const char __T10[63] = "int fe_surfactant1_str(fe_surfactant1_s *, int, double (*)[3])";
