# 1 "blue_phase_init.c"
static const char __T0[64];
static const char __T1[63];
static const char __T2[64];
static const char __T3[65];
static const char __T4[65];
static const char __T5[63];
static const char __T6[64];
static const char __T7[82];
static const char __T8[71];
static const char __T9[84];
static const char __T10[91];
static const char __T11[76];
static const char __T12[85];
static const char __T13[69];
static const char __T14[88];
static const char __T15[69];
static const char __T16[76];
static const char __T0[64] = "int blue_phase_O8M_init(coords_s *, fe_lc_param_s *, field_s *)";
static const char __T1[63] = "int blue_phase_O2_init(coords_s *, fe_lc_param_s *, field_s *)";
static const char __T2[64] = "int blue_phase_H2D_init(coords_s *, fe_lc_param_s *, field_s *)";
static const char __T3[65] = "int blue_phase_H3DA_init(coords_s *, fe_lc_param_s *, field_s *)";
static const char __T4[65] = "int blue_phase_H3DB_init(coords_s *, fe_lc_param_s *, field_s *)";
static const char __T5[63] = "int blue_phase_O5_init(coords_s *, fe_lc_param_s *, field_s *)";
static const char __T6[64] = "int blue_phase_DTC_init(coords_s *, fe_lc_param_s *, field_s *)";
static const char __T7[82] = "int blue_phase_BPIII_init(coords_s *, fe_lc_param_s *, field_s *, const double *)";
static const char __T8[71] = "int blue_phase_twist_init(coords_s *, fe_lc_param_s *, field_s *, int)";
static const char __T9[84] = "int blue_phase_nematic_init(coords_s *, fe_lc_param_s *, field_s *, const double *)";
static const char __T10[91] = "int blue_phase_active_nematic_init(coords_s *, fe_lc_param_s *, field_s *, const double *)";
static const char __T11[76] = "int lc_active_nematic_init_q2d(coords_s *, fe_lc_param_s *, field_s *, int)";
static const char __T12[85] = "int blue_phase_chi_edge(coords_s *, fe_lc_param_s *, field_s *, int, double, double)";
static const char __T13[69] = "int blue_phase_random_q_init(coords_s *, fe_lc_param_s *, field_s *)";
static const char __T14[88] = "int blue_phase_random_q_rectangle(coords_s *, fe_lc_param_s *, field_s *, int *, int *)";
static const char __T15[69] = "int blue_phase_cf1_init(coords_s *, fe_lc_param_s *, field_s *, int)";
static const char __T16[76] = "int blue_phase_random_cf1_init(coords_s *, fe_lc_param_s *, field_s *, int)";
