# 1 "colloid_io.c"
static const char __T0[85];
static const char __T1[36];
static const char __T2[59];
static const char __T3[36];
static const char __T4[53];
static const char __T5[51];
static const char __T6[70];
static const char __T7[73];
static const char __T8[74];
static const char __T9[50];
static const char __T10[52];
static const char __T11[53];
static const char __T12[75];
static const char __T13[64];
static const char __T14[76];
static const char __T15[65];
static const char __T16[54];
static const char __T17[55];
static const char __T18[55];
static const char __T19[55];
static const char __T20[62];
static const char __T21[47];
static const char __T0[85] = "int colloid_io_create(pe_s *, coords_s *, int *, colloids_info_s *, colloid_io_s **)";
static const char __T1[36] = "int colloid_io_free(colloid_io_s *)";
static const char __T2[59] = "int colloid_io_info_set(colloid_io_s *, colloids_info_s *)";
static const char __T3[36] = "int colloid_io_info(colloid_io_s *)";
static const char __T4[53] = "int colloid_io_count_colloids(colloid_io_s *, int *)";
static const char __T5[51] = "int colloid_io_write(colloid_io_s *, const char *)";
static const char __T6[70] = "int colloid_io_pack_buffer(colloid_io_s *, int, colloid_state_type *)";
static const char __T7[73] = "int colloid_io_write_buffer_ascii(_IO_FILE *, int, colloid_state_type *)";
static const char __T8[74] = "int colloid_io_write_buffer_binary(_IO_FILE *, int, colloid_state_type *)";
static const char __T9[50] = "int colloid_io_read(colloid_io_s *, const char *)";
static const char __T10[52] = "int colloid_io_read_header_ascii(_IO_FILE *, int *)";
static const char __T11[53] = "int colloid_io_read_header_binary(_IO_FILE *, int *)";
static const char __T12[75] = "int colloid_io_write_list_ascii(colloid_io_s *, int, int, int, _IO_FILE *)";
static const char __T13[64] = "int colloid_io_read_list_ascii(colloid_io_s *, int, _IO_FILE *)";
static const char __T14[76] = "int colloid_io_write_list_binary(colloid_io_s *, int, int, int, _IO_FILE *)";
static const char __T15[65] = "int colloid_io_read_list_binary(colloid_io_s *, int, _IO_FILE *)";
static const char __T16[54] = "int colloid_io_format_input_ascii_set(colloid_io_s *)";
static const char __T17[55] = "int colloid_io_format_input_binary_set(colloid_io_s *)";
static const char __T18[55] = "int colloid_io_format_input_serial_set(colloid_io_s *)";
static const char __T19[55] = "int colloid_io_format_output_ascii_set(colloid_io_s *)";
static const char __T20[62] = "int colloid_io_filename(colloid_io_s *, char *, const char *)";
static const char __T21[47] = "int colloid_io_check_read(colloid_io_s *, int)";
