# 1 "colloids.c"
# 169 "/usr/include/stdio.h" 3
extern struct _IO_FILE *stdout;
static const char __T0[72];
static const char __T1[43];
static const char __T2[54];
static const char __T3[44];
static const char __T4[55];
static const char __T5[52];
static const char __T6[54];
static const char __T7[46];
static const char __T8[51];
static const char __T9[50];
static const char __T10[53];
static const char __T11[63];
static const char __T12[58];
static const char __T13[62];
static const char __T14[61];
static const char __T15[48];
static const char __T16[50];
static const char __T17[51];
static const char __T18[48];
static const char __T19[79];
static const char __T20[72];
static const char __T21[63];
static const char __T22[53];
static const char __T23[54];
static const char __T24[80];
static const char __T25[74];
static const char __T26[50];
static const char __T27[48];
static const char __T28[55];
static const char __T29[55];
static const char __T30[70];
static const char __T31[60];
static const char __T32[58];
static const char __T33[53];
static const char __T34[52];
static const char __T35[54];
static const char __T36[62];
static const char __T37[53];
static const char __T38[53];
static const char __T39[75];
static const char __T40[79];
static const char __T41[60];
static const char __T42[73];
static const char __T43[57];
static const char __T44[59];
static const char __T0[72] = "int colloids_info_create(pe_s *, coords_s *, int *, colloids_info_s **)";
static const char __T1[43] = "void colloids_info_free(colloids_info_s *)";
static const char __T2[54] = "int colloids_info_recreate(int *, colloids_info_s **)";
static const char __T3[44] = "int colloids_memcpy(colloids_info_s *, int)";
static const char __T4[55] = "int colloids_info_nallocated(colloids_info_s *, int *)";
static const char __T5[52] = "int colloids_info_rho0(colloids_info_s *, double *)";
static const char __T6[54] = "int colloids_info_rho0_set(colloids_info_s *, double)";
static const char __T7[46] = "int colloids_info_map_init(colloids_info_s *)";
static const char __T8[51] = "int colloids_info_ntotal(colloids_info_s *, int *)";
static const char __T9[50] = "int colloids_info_ncell(colloids_info_s *, int *)";
static const char __T10[53] = "int colloids_info_lcell(colloids_info_s *, double *)";
static const char __T11[63] = "int colloids_info_cell_index(colloids_info_s *, int, int, int)";
static const char __T12[58] = "int colloids_info_map(colloids_info_s *, int, colloid **)";
static const char __T13[62] = "int colloids_info_map_old(colloids_info_s *, int, colloid **)";
static const char __T14[61] = "int colloids_info_map_set(colloids_info_s *, int, colloid *)";
static const char __T15[48] = "int colloids_info_map_update(colloids_info_s *)";
static const char __T16[50] = "int colloids_info_nhalo(colloids_info_s *, int *)";
static const char __T17[51] = "int colloids_info_nlocal(colloids_info_s *, int *)";
static const char __T18[48] = "int colloids_info_ntotal_set(colloids_info_s *)";
static const char __T19[79] = "int colloids_info_cell_list_head(colloids_info_s *, int, int, int, colloid **)";
static const char __T20[72] = "int colloids_info_cell_coords(colloids_info_s *, const double *, int *)";
static const char __T21[63] = "int colloids_info_insert_colloid(colloids_info_s *, colloid *)";
static const char __T22[53] = "int colloids_info_cell_list_clean(colloids_info_s *)";
static const char __T23[54] = "int colloids_info_update_cell_list(colloids_info_s *)";
static const char __T24[80] = "int colloids_info_add_local(colloids_info_s *, int, const double *, colloid **)";
static const char __T25[74] = "int colloids_info_add(colloids_info_s *, int, const double *, colloid **)";
static const char __T26[50] = "int colloid_create(colloids_info_s *, colloid **)";
static const char __T27[48] = "void colloid_free(colloids_info_s *, colloid *)";
static const char __T28[55] = "int colloids_info_q_local(colloids_info_s *, double *)";
static const char __T29[55] = "int colloids_info_v_local(colloids_info_s *, double *)";
static const char __T30[70] = "int colloids_info_cell_count(colloids_info_s *, int, int, int, int *)";
static const char __T31[60] = "int colloids_info_local_head(colloids_info_s *, colloid **)";
static const char __T32[58] = "int colloids_info_all_head(colloids_info_s *, colloid **)";
static const char __T33[53] = "int colloids_info_position_update(colloids_info_s *)";
static const char __T34[52] = "int colloids_info_list_all_build(colloids_info_s *)";
static const char __T35[54] = "int colloids_info_list_local_build(colloids_info_s *)";
static const char __T36[62] = "int colloids_info_climits(colloids_info_s *, int, int, int *)";
static const char __T37[53] = "int colloids_info_a0max(colloids_info_s *, double *)";
static const char __T38[53] = "int colloids_info_ahmax(colloids_info_s *, double *)";
static const char __T39[75] = "int colloids_info_count_local(colloids_info_s *, colloid_type_enum, int *)";
static const char __T40[79] = "void colloids_q_boundary_normal(colloids_info_s *, int, const int *, double *)";
static const char __T41[60] = "int colloid_rb(colloids_info_s *, colloid *, int, double *)";
static const char __T42[73] = "int colloid_rb_ub(colloids_info_s *, colloid *, int, double *, double *)";
static const char __T43[57] = "int colloids_info_rebuild_freq(colloids_info_s *, int *)";
static const char __T44[59] = "int colloids_info_rebuild_freq_set(colloids_info_s *, int)";
