# 1 "coords.c"
static const char __T0[35];
static const char __T1[26];
static const char __T2[24];
static const char __T3[39];
static const char __T4[24];
static const char __T5[26];
static const char __T6[24];
static const char __T9[41];
static const char __T10[36];
static const char __T17[39];
static const char __T18[45];
static const char __T20[34];
static const char __T23[43];
static const char __T24[48];
static const char __T25[50];
static const char __T26[36];
static const char __T30[40];
static const char __T31[40];
static const char __T32[27];
static const char __T34[29];
static const char __T0[35] = "int cs_create(pe_s *, coords_s **)";
static const char __T1[26] = "int cs_retain(coords_s *)";
static const char __T2[24] = "int cs_free(coords_s *)";
static const char __T3[39] = "int cs_target(coords_s *, coords_s **)";
static const char __T4[24] = "int cs_init(coords_s *)";
static const char __T5[26] = "int cs_commit(coords_s *)";
static const char __T6[24] = "int cs_info(coords_s *)";
static const char __T9[41] = "int cs_cart_neighb(coords_s *, int, int)";
static const char __T10[36] = "int cs_cart_comm(coords_s *, int *)";
static const char __T17[39] = "int cs_is_ok_decomposition(coords_s *)";
static const char __T18[45] = "int cs_rectilinear_decomposition(coords_s *)";
static const char __T20[34] = "int cs_nhalo_set(coords_s *, int)";
static const char __T23[43] = "int cs_ntotal_set(coords_s *, const int *)";
static const char __T24[48] = "int cs_periodicity_set(coords_s *, const int *)";
static const char __T25[50] = "int cs_decomposition_set(coords_s *, const int *)";
static const char __T26[36] = "int cs_reorder_set(coords_s *, int)";
static const char __T30[40] = "int cs_periodic_comm(coords_s *, int *)";
static const char __T31[40] = "int cs_cart_shift(int, int, int, int *)";
static const char __T32[27] = "int cs_pe_rank(coords_s *)";
static const char __T34[29] = "int cs_cart_rank(coords_s *)";
