# 1 "field.c"
static const char __T0[68];
static const char __T1[26];
static const char __T2[45];
static const char __T3[44];
static const char __T5[51];
static const char __T6[43];
static const char __T7[26];
static const char __T8[50];
static const char __T9[33];
static const char __T10[42];
static const char __T19[40];
static const char __T20[46];
static const char __T21[41];
static const char __T22[47];
static const char __T0[68] = "int field_create(pe_s *, coords_s *, int, const char *, field_s **)";
static const char __T1[26] = "int field_free(field_s *)";
static const char __T2[45] = "int field_init(field_s *, int, lees_edw_s *)";
static const char __T3[44] = "int field_memcpy(field_s *, cudaMemcpyKind)";
static const char __T5[51] = "int field_init_io_info(field_s *, int *, int, int)";
static const char __T6[43] = "int field_io_info(field_s *, io_info_s **)";
static const char __T7[26] = "int field_halo(field_s *)";
static const char __T8[50] = "int field_halo_swap(field_s *, field_halo_enum_t)";
static const char __T9[33] = "int field_leesedwards(field_s *)";
static const char __T10[42] = "int field_leesedwards_parallel(field_s *)";
static const char __T19[40] = "int field_read(_IO_FILE *, int, void *)";
static const char __T20[46] = "int field_read_ascii(_IO_FILE *, int, void *)";
static const char __T21[41] = "int field_write(_IO_FILE *, int, void *)";
static const char __T22[47] = "int field_write_ascii(_IO_FILE *, int, void *)";
