# 1 "leesedwards.c"
static const char __T0[74];
static const char __T1[34];
static const char __T2[32];
static const char __T3[34];
static const char __T4[49];
static const char __T5[43];
static const char __T6[48];
static const char __T7[48];
static const char __T8[44];
static const char __T9[51];
static const char __T14[32];
static const char __T15[39];
static const char __T16[34];
static const char __T25[39];
static const char __T26[45];
static const char __T27[66];
static const char __T40[60];
static const char __T41[52];
static const char __T0[74] = "int lees_edw_create(pe_s *, coords_s *, lees_edw_info_s *, lees_edw_s **)";
static const char __T1[34] = "int lees_edw_retain(lees_edw_s *)";
static const char __T2[32] = "int lees_edw_free(lees_edw_s *)";
static const char __T3[34] = "int lees_edw_commit(lees_edw_s *)";
static const char __T4[49] = "int lees_edw_target(lees_edw_s *, lees_edw_s **)";
static const char __T5[43] = "int lees_edw_nplane_set(lees_edw_s *, int)";
static const char __T6[48] = "int lees_edw_plane_uy_set(lees_edw_s *, double)";
static const char __T7[48] = "int lees_edw_oscillatory_set(lees_edw_s *, int)";
static const char __T8[44] = "int lees_edw_toffset_set(lees_edw_s *, int)";
static const char __T9[51] = "int lees_edw_init(lees_edw_s *, lees_edw_info_s *)";
static const char __T14[32] = "int lees_edw_info(lees_edw_s *)";
static const char __T15[39] = "int lees_edw_init_tables(lees_edw_s *)";
static const char __T16[34] = "int lees_edw_checks(lees_edw_s *)";
static const char __T25[39] = "int lees_edw_comm(lees_edw_s *, int *)";
static const char __T26[45] = "int lees_edw_plane_comm(lees_edw_s *, int *)";
static const char __T27[66] = "int lees_edw_jstart_to_mpi_ranks(lees_edw_s *, int, int *, int *)";
static const char __T40[60] = "int lees_edw_buffer_dy(lees_edw_s *, int, double, double *)";
static const char __T41[52] = "int lees_edw_buffer_du(lees_edw_s *, int, double *)";
