# 1 "runtime.c"
static const char __T0[31];
static const char __T1[20];
static const char __T2[45];
static const char __T3[57];
static const char __T4[20];
static const char __T5[29];
static const char __T6[56];
static const char __T7[50];
static const char __T8[63];
static const char __T9[57];
static const char __T10[68];
static const char __T11[36];
static const char __T12[34];
static const char __T13[47];
static const char __T14[49];
static const char __T0[31] = "int rt_create(pe_s *, rt_s **)";
static const char __T1[20] = "int rt_free(rt_s *)";
static const char __T2[45] = "int rt_read_input_file(rt_s *, const char *)";
static const char __T3[57] = "int rt_add_key_value(rt_s *, const char *, const char *)";
static const char __T4[20] = "int rt_info(rt_s *)";
static const char __T5[29] = "int rt_key_broadcast(rt_s *)";
static const char __T6[56] = "int rt_double_parameter(rt_s *, const char *, double *)";
static const char __T7[50] = "int rt_int_parameter(rt_s *, const char *, int *)";
static const char __T8[63] = "int rt_double_parameter_vector(rt_s *, const char *, double *)";
static const char __T9[57] = "int rt_int_parameter_vector(rt_s *, const char *, int *)";
static const char __T10[68] = "int rt_string_parameter(rt_s *, const char *, char *, unsigned int)";
static const char __T11[36] = "int rt_switch(rt_s *, const char *)";
static const char __T12[34] = "int rt_active_keys(rt_s *, int *)";
static const char __T13[47] = "int rt_add_key_pair(rt_s *, const char *, int)";
static const char __T14[49] = "int rt_look_up_key(rt_s *, const char *, char *)";
